# Generated by Django 5.1.6 on 2026-06-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompagnieAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_iata', models.CharField(max_length=3, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='compagnies/')),
            ],
            options={
                'verbose_name': 'Compagnie Aérienne',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vol', models.CharField(max_length=10)),
                ('ville_depart', models.CharField(max_length=100)),
                ('code_depart', models.CharField(max_length=3)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('code_arrivee', models.CharField(max_length=3)),
                ('date_depart', models.DateTimeField()),
                ('date_arrivee', models.DateTimeField()),
                ('nombre_escales', models.IntegerField(choices=[(0, 'Direct'), (1, '1 escale'), (2, '2 escales')], default=0)),
                ('prix_economique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_affaires', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_premiere', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('places_economique', models.IntegerField(default=0)),
                ('places_affaires', models.IntegerField(default=0)),
                ('places_premiere', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('complet', 'Complet'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='actif', max_length=10)),
                ('est_populaire', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vols', to='vols.compagnieaerienne')),
            ],
            options={
                'verbose_name': 'Vol',
                'ordering': ['date_depart'],
            },
        ),
    ]
