# Generated by Django 5.1.6 on 2026-06-13 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vols', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=10, unique=True)),
                ('classe', models.CharField(choices=[('economique', 'Économique'), ('affaires', 'Affaires'), ('premiere', 'Première Classe')], default='economique', max_length=12)),
                ('nombre_passagers', models.IntegerField(default=1)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('billet_emis', 'Billet émis'), ('annulee', 'Annulée')], default='en_attente', max_length=15)),
                ('notes_admin', models.TextField(blank=True)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('vol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='vols.vol')),
            ],
            options={
                'verbose_name': 'Réservation',
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('M', 'Monsieur'), ('F', 'Madame')], max_length=1)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=50)),
                ('numero_passeport', models.CharField(max_length=20)),
                ('expiration_passeport', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passagers', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Passager',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('carte', 'Carte bancaire'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('mtn_momo', 'MTN MoMo')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=12)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paiement', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Paiement',
            },
        ),
    ]
