# Generated by Django 5.1.6 on 2026-07-02 06:17

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', accounts.models.UtilisateurManager()),
            ],
        ),
    ]
